services:
  database:
    image: henryfranz/moveon-database:1.0
    container_name: moveon-database
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306
    networks:
      - moveon-network
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - moveon-database-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
  website:
    image: henryfranz/moveon-web-site:1.0
    container_name: moveon-web-site
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - moveon-network
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
  etl:
    image: henryfranz/moveon-etl:1.0
    container_name: moveon-etl
    networks:
      - moveon-network
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy

networks:
  moveon-network:
    driver: bridge

volumes:
  moveon-database-data:
